### ISSUE TITLE
[fix] schema modify

### ISSUE THREAD

**Issue by kys88** [codestates/Puzzle_Server#48]
### ISSUE
- Group:  `client`, `server`, `sr`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### TODO
1. [ ] project 테이블과 image 테이블 합치기
2. [ ] 합친 버전 pull 해서 ec2에 적용하기
3. [ ] project / update / :id API 작성하기

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
